config/routes.rb
Rails.application.routes.draw do

  get 'uno' => 'uno#index', as: :uno
  post 'uno/crawle_instagram', as: :crawle_instagram

  get 'instagram/index'

  resources :articles
  resources :tags

  root 'contents#top'

  get 'calendar' => 'contents#calendar', as: :calendar
  get 'all' => 'contents#all_list', as: :all_list
  get ':id' => 'contents#list', as: :list
  get ':id/photo_list' => 'contents#photo_list', as: :photo_list

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_tags
  def top
    @articles = Article.recently.limit(10)
  end

  def list
    page = params[:page].to_i > 0 ? params[:page].to_i : 1
    @tag = Tag.friendly.find(params[:id])
    @articles = @tag.related_articles.page(page).per(20)
    add_crumb "#{@tag.display_name}"
  end
  def photo_list
    @tag = Tag.friendly.find(params[:id])
    @articles = @tag.related_articles
    add_crumb "#{@tag.display_name}の写真一覧"
  end
  def all_list
    page = params[:page].to_i > 0 ? params[:page].to_i : 1
    article_rel =Article.recently 
    if params[:date].present?
      date = Date.parse(params[:date])
      article_rel = article_rel.where("post_date between ? and ?", date.beginning_of_day, date.end_of_day)
      @title = "#{date.strftime("%Y/%-m/%-d")}の記事"
    end
    if params[:kw].present?
      @kw = params[:kw].to_s.strip
      article_rel = article_rel.where('title like ? or body like ?', "%#{@kw}%", "%#{@kw}%")
      @title = "キーワード「#{@kw}」を含む記事"
    end
    @articles = article_rel.page(page).per(10)
    @title ||="すべての記事 #{@articles.current_page}ページ"
    add_crumb @title 
  end
  def calendar
    if params[:date].present?
      @date = Date.parse(params[:date])
    else
      @date = Time.now
    end
    render layout: false
  end

  private
  def set_tags
    @tags = Tag.for_top

  end
end

app/views/contents/_list_part.html.slim
- articles.each do |article|
  = render partial: 'shared/article', locals: {article: article, tag: tag}

app/views/contents/all_list.html.slim
- content_for :head
  meta name="robots" content="noindex,nofollow"
- provide :title, "#{@title} | シンプルコーデブログ -unobox-"
- provide :meta_desc, "#{@title}"
- provide :h1, "#{@title}"
.l-contents
  = render partial: 'shared/side_column'
  .l-column-main
    = render partial: "list_part", locals: {articles: @articles, tag: nil}
    = paginate(@articles)

app/views/contents/calendar.html.slim
= render_calendar(@date)

app/views/contents/list.html.slim
- provide :title, "#{@tag.display_name}のコーディネート | シンプルコーデブログ -unobox-"
- provide :meta_desc, "#{@tag.display_name}のコーディネート一覧。東京在住のOL・unoがシンプルコーデを紹介するブログです。MHL.や無印良品、GU（ジーユー）、ユニクロを中心としたコーデの置き画をInstagramを中心に投稿中！"
- provide :h1, "#{@tag.display_name}のコーディネート"
- if @articles.current_page > 1 || (@tag && !@tag.for_display)
  - content_for :head
    meta name="robots" content="noindex,nofollow"
- content_for :desc
  = @tag.description
.l-contents
  = render partial: 'shared/side_column'
  .l-column-main
    = link_to "写真一覧", photo_list_path(@tag), rel: "nofollow"
    = render partial: "list_part", locals: {articles: @articles, tag: @tag}
    = paginate(@articles)

app/views/contents/photo_list.html.slim
- provide :title, "#{@tag.display_name}の写真一覧 | シンプルコーデブログ -unobox-"
- provide :h1, "#{@tag.display_name}の写真一覧"
- content_for :head
  meta name="robots" content="noindex,nofollow"
.l-contents
  = render partial: 'shared/side_column'
  .l-column-main
    .photo-list
      - @articles.each do |article|
        .photo-list__item
          = link_to image_tag(article.image_url_inside), article_path(article)

app/views/contents/top.html.slim
- provide :title, "シンプルコーデブログ -unobox-"
- provide :meta_desc, "MHL.や無印良品、GU（ジーユー）、ユニクロを中心としたコーデの置き画をInstagramを中心に投稿中！東京在住のOL・unoがシンプルコーデを紹介するブログです。"
- content_for :desc
  | MHL.や無印良品、GU（ジーユー）、ユニクロを中心としたコーデの置き画をInstagramを中心に投稿中！
  br
  | 東京在住のOL・unoがシンプルコーデを紹介するブログです。
.l-contents
  = render partial: 'shared/side_column'
  .l-column-main
    = render partial: "list_part", locals: {articles: @articles, tag: nil}
    p.more-link
      = link_to "もっと見る", all_list_path(page: 2), rel: "nofollow"