config/routes.rb
Rails.application.routes.draw do

  get 'uno' => 'uno#index', as: :uno
  post 'uno/crawle_instagram', as: :crawle_instagram

  get 'instagram/index'

  resources :articles
  resources :tags

  root 'contents#top'

  get 'calendar' => 'contents#calendar', as: :calendar
  get 'all' => 'contents#all_list', as: :all_list
  get ':id' => 'contents#list', as: :list
  get ':id/photo_list' => 'contents#photo_list', as: :photo_list

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags

  after_save :set_tags
  before_save  :set_body_for_display
  before_create :set_body_for_display

  attr_accessor :twitter_post
  scope :recently, ->{where(is_public: true).order("post_date desc")}

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  has_attached_file :image2, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  has_attached_file :image3, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :image2, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :image3, :content_type => /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: [:image, :image2, :image3], :less_than => 2.megabytes
  
  TAG_REGEXP = /(?:#.+?\s|#.+?$)/


  def set_tags
    tag_seeds = body.scan(TAG_REGEXP)
    tags = tag_seeds.map{|t|t.gsub(/#|\s/, "")}
    tags.each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name) do |t|
        t.name_en = t.name
      end
      ArticleTag.find_or_create_by(article: self, tag: tag)
    end
  end
  def set_body_for_display
    self.body_for_display = body.gsub(TAG_REGEXP, "").gsub(/\*/, "").gsub(/\.\r\n/, "\r\n").gsub(/\.\n/, "\n")
  end

  def post_image_to_twitter
    DownloadImage.save_image(image_url, self.id.to_s, "images")
    dir_name = Rails.root.join("public").join("system").join("images")
    file_path = dir_name.join(self.id.to_s) 
    url = Rails.application.routes.url_helpers.article_url(self, host: "unobox-blog.net", protocol: :https) 
    surl = Bitly.client.shorten(url).short_url
    msg =  ApplicationController.helpers.truncate(body_for_display.to_str.html_safe , length: 80) +  " #{surl}"
    TwitterPost.post_with_media(file_path, msg)
  end

  def image_url_inside
    #"/system/review_images/#{image_fname}"
    if image.present?
      image.url
    else
      image_url
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
 
  before_action :authenticate, except: [:show]
 

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order("post_date desc")
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @tags = Tag.for_top
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    Rails.logger.debug article_params.pretty_inspect
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :body2, :body3, :post_date, :twitter_post, :image, :image2, :image3, :is_public, :image_url)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message
  .form
    .form__item
      .form__title
        = f.label :image_url
      .form__input
        = f.text_field :image_url, class: "c-textfield c-textfield--full form__textarea-imageurl"
    .form__item
      .form__title
        = f.label :post_date
      .form__input
        = f.datetime_select :post_date, class: "c-textfield form__textarea"
    .form__item
      .form__title
        = f.label :image
      .form__input
        = f.file_field :image
    .form__item
      .form__title
        = f.label :body
      .form__input
        = f.text_area :body, class: "c-textfield c-textfield--full form__textarea-body", placeholder: "本文を入力"
    .form__item
      .form__title
        = f.label :image2
      .form__input
        = f.file_field :image2
    .form__item
      .form__title
        = f.label :body2
      .form__input
        = f.text_area :body2, class: "c-textfield c-textfield--full form__textarea-body", placeholder: "本文を入力"
    .form__item
      .form__title
        = f.label :image3
      .form__input
        = f.file_field :image3
    .form__item
      .form__title
        = f.label :body3
      .form__input
        = f.text_area :body3, class: "c-textfield c-textfield--full form__textarea-body", placeholder: "本文を入力"
    .form__item
      .form__title
        = f.label :is_public, "公開"
      .form__input
        = f.check_box :is_public, {}, "true", "false"
    .form__item
      .form__title
        = f.label :twitter_post, "Twitterにも投稿する"
      .form__input
        = f.check_box :twitter_post, class: "c-checkbox form__checkbox"
  .post-action-btn = f.submit "投稿する", class: "c-btn post-action-btn__target"

app/views/articles/edit.html.slim
.l-contents
  .l-column-full
    .edit-back
      = link_to '記事一覧へ戻る', articles_path, class: "edit-back__target"
    .c-admin-title
      h1 記事を編集
      .c-admin-title__option
        = link_to '[ プレビュー ]', @article, target: "_blank"
    == render 'form'

app/views/articles/index.html.slim
.l-contents
  .l-column-full
    h1.c-admin-title 記事一覧
    p.new-entry
      = link_to '新しく記事を投稿する', new_article_path, class: "c-btn"

    table.edit-table
      thead.edit-table__thead
        th.edit-table__thead-image
        th.edit-table__thead-status 公開中
        th.edit-table__thead-body 記事内容
        th.edit-table__thead-post-date 投稿日時
        th.edit-table__thead-action-link
        th.edit-table__thead-action-link
        th.edit-table__thead-action-link

      tbody.edit-table__tbody
        - @articles.each do |article|
          tr.articles-list
            td.articles-list__image = image_tag article.image_url_inside
            td.articles-list__public = article.is_public
            td.articles-list__body = article.body
            td.articles-list__post-date = article.post_date.strftime("%Y/%-m/%-d")
            td.articles-list__action-link = link_to '詳細', article
            td.articles-list__action-link = link_to '編集', edit_article_path(article)
            td.articles-list__action-link = link_to '削除', article, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/articles/new.html.slim
.l-contents
  .l-column-full
    .edit-back
      = link_to '記事一覧へ戻る', articles_path, class: "edit-back__target"
    h1.c-admin-title 記事を新規投稿
    == render 'form'

app/views/articles/show.html.slim
= provide :title, "#{@article.post_date.strftime("%Y.%-m.%-d %a").downcase}の記事 | unobox-blog"
= content_for :head do
  meta[name="robots" content="noindex,nofollow"]
.l-contents
  = render partial: 'shared/side_column'
  .l-column-main
    = render partial: 'shared/article', locals: {article: @article, tag: nil}
    = link_to "記事一覧へ", root_path, class: "back-link"