config/routes.rb
Rails.application.routes.draw do

  get 'uno' => 'uno#index', as: :uno
  post 'uno/crawle_instagram', as: :crawle_instagram

  get 'instagram/index'

  resources :articles
  resources :tags

  root 'contents#top'

  get 'calendar' => 'contents#calendar', as: :calendar
  get 'all' => 'contents#all_list', as: :all_list
  get ':id' => 'contents#list', as: :list
  get ':id/photo_list' => 'contents#photo_list', as: :photo_list

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  include FriendlyId
  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags
  has_many :related_articles, ->(tag){order("articles.post_date desc" )}, source: :article, through: :article_tags

  scope :for_top, ->{where("for_display = true").joins(:article_tags).group("tags.id").order("count(article_tags.id) desc")}
  scope :for_display, ->{where("for_display = true").order("name asc")}
  scope :dont_display, ->{where("for_display = false and for_body_display = true").order("name asc")}

  friendly_id :name_en, :use => [:slugged]

  def display_name
    name.gsub(/_/, " ")
  end

  def name_regexp
    name.split(/_/).join("|")
  end

  private

  def should_generate_new_friendly_id?
    slug.blank? || name_en_changed? || super
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :authenticate

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.select("tags.*, count(article_tags.id) as article_count").joins("LEFT OUTER JOIN article_tags on article_tags.tag_id = tags.id").group("tags.id").order("for_display desc, for_body_display, article_count desc")
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to action: :index, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :name_en, :description, :for_display, :for_body_display)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.slim
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      ul
        - @tag.errors.full_messages.each do |message|
          li = message

  .form
    .form__item
      .form__title
        = f.label :name
      .form__input
        = f.text_field :name, class: "c-textfield c-textfield--full", placeholder: "タグ名を入力"
    .form__item
      .form__title
        = f.label :name_en
      .form__input
        = f.text_field :name_en, class: "c-textfield c-textfield--full", placeholder: "タグ名（英語）を入力"
    .form__item
      .form__title
        = f.label :slug, "url(自動更新)"
      .form__input
        = f.text_field :slug, readonly: true, class: "c-textfield c-textfield--full"
    .form__item
      .form__title
        = f.label :description
      .form__input
        = f.text_area :description, class: "c-textfield c-textfield--full  form__textarea-body", placeholder: "タグの説明を入力"
    .form__item
      .form__title
        = f.label :for_display, "サイト上に表示する"
      .form__input
        = f.check_box :for_display
    .form__item
      .form__title
        = f.label :for_body_display, "本文に表示する"
      .form__input
        = f.check_box :for_body_display
  .post-action-btn = f.submit "投稿する", class: "c-btn post-action-btn__target"

app/views/tags/edit.html.slim
.l-contents
  .l-column-main
    h1.c-admin-title タグを編集

    == render 'form'

    = link_to 'Show', @tag
    '|
    = link_to 'Back', tags_path

app/views/tags/index.html.slim
.l-contents
  .l-column-full
    h1.c-admin-title.edit-table__title タグ一覧
    p.new-entry
      = link_to '新しくタグを登録する', new_tag_path, class: "c-btn"

    table.edit-table
      thead.edit-table__thead
        th.edit-table__thead-id ID
        th.edit-table__thead-title タグ名
        th.edit-table__thead-count 記事数
        th.edit-table__thead-status サイト上に表示
        th.edit-table__thead-status 本文に表示
        th.edit-table__thead-action-link 記事一覧
        th.edit-table__thead-body タグ説明
        th.edit-table__thead-action-link
        th.edit-table__thead-action-link

      tbody.edit-table__tbody
        - @tags.each do |tag|
          tr.articles-list
            td.articles-list__id = tag.id
            td.articles-list__title = tag.name
            td.articles-list__count = tag.article_count
            td.articles-list__status = tag.for_display
            td.articles-list__status = tag.for_body_display
            td.articles-list__action-link = link_to "記事一覧", list_path(tag)
            td.articles-list__body = tag.description
            td.articles-list__action-link = link_to 'タグ編集', edit_tag_path(tag)
            td.articles-list__action-link = link_to 'タグ削除', tag, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/tags/new.html.slim
.l-contents
  .l-column-main
    h1.c-admin-title タグを新規登録

    == render 'form'

    = link_to 'Back', tags_path

app/views/tags/show.html.slim
p#notice = notice

p
  strong Name:
  = @tag.name
p
  strong Desc:
  = @tag.description

= link_to 'Edit', edit_tag_path(@tag)
'|
= link_to 'Back', tags_path